# Jekyll Configuration for Node-RED Dashboard 2 UI Scheduler Documentation

title: "Node-RED Dashboard 2 UI Scheduler"
description: "Official documentation for Node-RED Dashboard 2 UI Scheduler"
author: "cgjgh"
baseurl: "/node-red-dashboard-2-ui-scheduler" # The subpath of your site, e.g. /blog
url: "https://cgjgh.github.io/node-red-dashboard-2-ui-scheduler"
github_repo_url: "https://github.com/cgjgh/node-red-dashboard-2-ui-scheduler"

# Themes and Plugins
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - "README.md"
  - "package.json"
  - "LICENSE"
  - "cypress/"
  - "scripts/"
  - "assets/"

# Menu configuration (if using a theme that supports navigation)
menu:
  - title: "Home"
    url: "/wiki/Home"
  - title: "Installation"
    url: "/wiki/Installation"
  - title: "Configuration"
    url: "/wiki/Configuration"
  - title: "Usage"
    url: "/wiki/Usage"
  - title: "Features"
    url: "/wiki/Features"
  - title: "Development"
    url: "/wiki/Development"
  - title: "License"
    url: "/wiki/License"
  - title: "Acknowledgements"
    url: "/wiki/Acknowledgements"

# Enable pagination
paginate: 10
